# Generated by Django 4.2.7 on 2023-12-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('request_type', models.CharField(choices=[('handover', 'Handover'), ('support', 'Support')], default='handover', max_length=10)),
                ('level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceprovided', models.CharField(choices=[('request for non-fixed', 'Request for non-Fixed'), ('handover', 'Handover'), ('return old property', 'Return Old Property')], max_length=100)),
                ('productname', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('fixed', 'Fixed'), ('non-fixed', 'Non-Fixed')], max_length=100)),
                ('detailed_description', models.TextField()),
                ('measurement', models.CharField(max_length=100)),
                ('OfficialsRemarkforRequest', models.TextField()),
                ('NumberofItems', models.IntegerField(default=0)),
                ('PriceofEach', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PropertiesNow', models.CharField(choices=[('working', 'Working'), ('Notworking', 'NotWorking ')], max_length=100)),
                ('Remark', models.CharField(max_length=100)),
                ('totalcost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supportdocument', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('serialNo', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('Fixed', 'Fixed'), ('Non-fixed', 'Non-fixed')], max_length=20, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalprice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
    ]
