# Generated by Django 4.2.7 on 2023-12-10 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_alter_admin_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('measurement', models.CharField(max_length=100)),
                ('NumberofItems', models.IntegerField()),
                ('PriceofEach', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalcost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('serial_number', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
                ('Remark', models.TextField()),
                ('supportdocument', models.FileField(upload_to='support_documents/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterField(
            model_name='admin',
            name='request_type',
            field=models.CharField(choices=[('handover', 'Handover'), ('request', 'request'), ('return', 'return')], default='handover', max_length=10),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
