# Generated by Django 4.2.7 on 2023-12-10 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_handover_alter_admin_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handover',
            options={'verbose_name_plural': 'Handover'},
        ),
    ]
