# Generated by Django 4.2.7 on 2023-12-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_handover_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover',
            name='higher_official1_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='handover',
            name='higher_official2_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='handover',
            name='higher_official3_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='handover',
            name='owner_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='handover',
            name='participant_approved',
            field=models.BooleanField(default=False),
        ),
    ]
