# Generated by Django 4.2.7 on 2023-12-11 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handover',
            name='higher_official1_approved',
        ),
        migrations.RemoveField(
            model_name='handover',
            name='higher_official2_approved',
        ),
        migrations.RemoveField(
            model_name='handover',
            name='higher_official3_approved',
        ),
        migrations.RemoveField(
            model_name='handover',
            name='owner_approved',
        ),
        migrations.RemoveField(
            model_name='handover',
            name='participant_approved',
        ),
    ]
