# Generated by Django 4.2.7 on 2023-12-13 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0014_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('experience', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='handover',
            name='current_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='handover',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
