# Generated by Django 4.2.7 on 2023-12-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
