# Generated by Django 4.2.7 on 2023-12-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
