# Generated by Django 4.2.7 on 2023-12-14 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_task_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
