# Generated by Django 4.2.7 on 2023-12-14 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_delete_admin_delete_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model20fixedrequest',
            name='approval_status',
        ),
        migrations.AddField(
            model_name='model20fixedrequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver', models.CharField(max_length=100)),
                ('approval_message', models.TextField()),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.model20fixedrequest')),
            ],
        ),
    ]
