# Generated by Django 4.2.7 on 2023-12-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_model20fixedrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model20fixedrequest',
        ),
    ]
