# Generated by Django 4.2.7 on 2023-12-16 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Approval',
        ),
    ]
