# Generated by Django 4.2.7 on 2023-12-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_delete_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_name', models.CharField(max_length=100)),
                ('approval_status', models.CharField(max_length=100)),
                ('date_of_approval', models.DateField(auto_now=True)),
            ],
        ),
    ]
