# Generated by Django 4.2.7 on 2023-12-16 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_approval'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
