# Generated by Django 4.2.7 on 2023-12-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='approval_status',
        ),
        migrations.AlterField(
            model_name='approval',
            name='approver_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='approval',
            name='date_of_approval',
            field=models.DateField(),
        ),
    ]
