# Generated by Django 4.2.7 on 2023-12-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_remove_approval_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approver_name',
            field=models.CharField(max_length=100),
        ),
    ]
