# Generated by Django 4.2.7 on 2023-12-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_alter_approval_approver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='totalprice',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=10),
        ),
    ]
